server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.tugsef.services.ticketservice

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app
  jpa:
    database: mysql
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: create

management:
  tracing:
    sampling:
      probability: 1.0