version: '3.9'

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra
      
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: microservice-app
    ports:
      - '3306:3306'
      
  elasticsearch:
    image: elasticsearch:7.17.10
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
   

  msrabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=tugsef
      - RABBITMQ_DEFAULT_PASS=tugsef

    
      
    
  
     