spring:
  config:
    import: "optional:configserver:http://   -service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: ticket-service
  config:
    import: "optional:configserver:http://localhost:8088"